@startuml
title Nasjonalt grunnkart for arealanalyse (Testversjon 2) - Objekttyper

skinparam class {
  AttributeIconSize 0
}

package "Objekttyper" {

  class Fylker <<featureType>> {
    + objid [0..1] : Integer
    + objtype [0..1] : CharacterString
    + lokalid [0..1] : CharacterString
    + navnerom [0..1] : CharacterString
    + versjonid [0..1] : CharacterString
    + oppdateringsdato [0..1] : DateTime
    + gyldigfra [0..1] : Date
    + gyldigtil [0..1] : Date
    + datafangstdato [0..1] : DateTime
    + datauttaksdato [0..1] : DateTime
    + opphav [0..1] : CharacterString
    + fylkesnummer [0..1] : CharacterString
    + fylkesnavn [0..1] : CharacterString
    + samiskforvaltningsomrade [0..1] : Boolean
  }

  class Fylkesgrenser <<featureType>> {
    + objid [0..1] : Integer
    + objtype [0..1] : CharacterString
    + lokalid [0..1] : CharacterString
    + navnerom [0..1] : CharacterString
    + versjonid [0..1] : CharacterString
    + oppdateringsdato [0..1] : DateTime
    + gyldigfra [0..1] : Date
    + gyldigtil [0..1] : Date
    + datafangstdato [0..1] : DateTime
    + malemetode [0..1] : CharacterString
    + noyaktighet [0..1] : Integer
    + datauttaksdato [0..1] : DateTime
    + opphav [0..1] : CharacterString
    + avgrensningstype [0..1] : CharacterString
  }

  class Kommuner <<featureType>> {
    + objid [0..1] : Integer
    + objtype [0..1] : CharacterString
    + lokalid [0..1] : CharacterString
    + navnerom [0..1] : CharacterString
    + versjonid [0..1] : CharacterString
    + oppdateringsdato [0..1] : DateTime
    + gyldigfra [0..1] : Date
    + gyldigtil [0..1] : Date
    + datafangstdato [0..1] : DateTime
    + datauttaksdato [0..1] : DateTime
    + opphav [0..1] : CharacterString
    + kommunenummer [0..1] : CharacterString
    + kommunenavn [0..1] : CharacterString
    + samiskforvaltningsomrade [0..1] : Boolean
  }

  class Kommunegrenser <<featureType>> {
    + objid [0..1] : Integer
    + objtype [0..1] : CharacterString
    + lokalid [0..1] : CharacterString
    + navnerom [0..1] : CharacterString
    + versjonid [0..1] : CharacterString
    + oppdateringsdato [0..1] : DateTime
    + gyldigfra [0..1] : Date
    + gyldigtil [0..1] : Date
    + datafangstdato [0..1] : DateTime
    + malemetode [0..1] : CharacterString
    + noyaktighet [0..1] : Integer
    + datauttaksdato [0..1] : DateTime
    + opphav [0..1] : CharacterString
    + avgrensningstype [0..1] : CharacterString
  }
}

@enduml
